version: 1
disable_existing_loggers: False

formatters:
  out:
    format: "%(asctime)s -- %(name)s -- %(levelname)s -- %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: out
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: out
    filename: rolling.log
    maxBytes: 5242880
    backupCount: 4
    encoding: utf8

  warn_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: out
    filename: rolling.log
    maxBytes: 5242880
    backupCount: 4
    encoding: utf8

root:
  level: DEBUG
  handlers: [console, debug_file_handler, warn_file_handler]